### ISSUE TITLE
Theme improvements request

### ISSUE THREAD

**Issue by Pizzacutter-at-tty3** [CritLoren/Darktable-MD3#1]
I like this theme in general especially highlighting dangerous actions and the on/off buttons style, but colors are badly chosen.

Dark UI in combination with white Darkroom background will mess up anyone's color perception. Darktable has neutral grey theme for this specific reason - it will not break your color perception and brightness / saturation / contrast of the final image will be correct.

Would you make a neutral grey version, something like Darktable-elegant-grey?

And also, I noticed that hovering a scrollbar makes it grow and the related list of items also grows in a jittery way.

**Comment by CritLoren** [comment]
Hello, yeah the scrollbar is a bit iffy, I noticed after uploading that my smart way of keeping the layout from moving while visually changing the size of the scrollbar was not so smart haha

As for colours I added `md3-base-colours.css` that removes most of the colour overrides I added. I need to tweak the colours of the reset buttons to match tho
