### ISSUE TITLE
[REQUEST] Instalation instructions

### ISSUE THREAD

**Issue by ItaloCunhaBueno** [CritLoren/Darktable-MD3#2]
Could you please add installarion instructions? It seems the base.css file require a "darktable.css" that I could not find, thus I could not imply where to put the files. Instructions on where to put the files and how to load them would be nice. Thanks.

**Comment by CritLoren** [comment]
It should come with the base darktable install, though if you're on Linux it's not properly recognised oddly enough so you have to point to the install location. You can also grab it from https://github.com/darktable-org/darktable/blob/master/data/themes/darktable.css

**Comment by ItaloCunhaBueno** [comment]
I'm on Windows, in darktable's install folder there's no .css file, however in it's appdata folder there's a "user.css" file.
My darktable version is 4.9 nightly

**Comment by ItaloCunhaBueno** [comment]
Nevermind, found it in "C:\Program Files\darktable\share\darktable\themes"
